[MOSIP-39977] Update docker-build.yml
Signed-off-by: Chandra Keshav Mishra <chandrakeshavmishra@gmail.com>

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -23,7 +23,11 @@ on:
         default: false
       SQUASH_LAYERS:
         required: false
-        type: string   
+        type: string
+      GraalVM:
+        required: false
+        type: boolean
+        default: false
 
     secrets:
       RELEASE_DOCKER_HUB:
@@ -36,8 +40,54 @@ on:
         required: true
 
 jobs:
+  build-docker-warning:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Select Dockerfile
+        run: |
+            GRAALVM=$(echo "${{ toJSON(inputs.GraalVM) }}" | tr -d '"')
+            echo "GRAALVM=$GRAALVM" >> $GITHUB_ENV
+      
+            if [[ "$GRAALVM" == "true" ]]; then
+              echo "DOCKERFILE_NAME=Dockerfile_Graalvm" >> $GITHUB_ENV
+            else
+              echo "DOCKERFILE_NAME=Dockerfile" >> $GITHUB_ENV
+            fi
+
+
+      - name: Check Dockerfile for forbidden organizations and tags
+        if: |
+          (github.event_name == 'push' && startsWith(github.ref_name, 'release')) ||
+          (github.event_name == 'pull_request' && startsWith(github.base_ref, 'release')) ||
+          (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/release'))
+        run: |
+          cd ${{ inputs.SERVICE_LOCATION }}
+          if [ ! -f $DOCKERFILE_NAME ]; then
+            echo "Error: $DOCKERFILE_NAME not found."
+            exit 1
+          fi
+          forbidden_found=false
+          if grep -E "FROM (mosipdev|mosipqa)/" $DOCKERFILE_NAME; then
+            echo "Error: $DOCKERFILE_NAME contains forbidden base image from 'mosipdev' or 'mosipqa'."
+            forbidden_found=true
+          fi
+          if grep -E "FROM .*:(latest|develop)" $DOCKERFILE_NAME; then
+            echo "Error: $DOCKERFILE_NAME contains forbidden base image tag 'latest' or 'develop'."
+            forbidden_found=true
+          fi
+          if [ "$forbidden_found" = true ]; then
+            echo "Error: Forbidden base images or tags detected."
+            exit 1
+          else
+            echo "Dockerfile check passed."
+          fi
+
   build-dockers:
     runs-on: ubuntu-latest
+    needs: build-docker-warning
     env:
       NAMESPACE: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
       SERVICE_LOCATION: ${{ inputs.SERVICE_LOCATION }}
@@ -45,24 +95,23 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+
       - uses: actions/download-artifact@v4
-        if: ${{ ( inputs.BUILD_ARTIFACT != 'false' ) }}
+        if: ${{ inputs.BUILD_ARTIFACT != 'false' }}
         with:
           name: ${{ inputs.BUILD_ARTIFACT }}
           path: ./
 
       - name: Install docker-squash
-        run: pip install docker-squash    
+        run: pip install docker-squash
 
       - name: Setup branch and env
         run: |
-          # Strip git ref prefix from version
           echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
           echo "GPG_TTY=$(tty)" >> $GITHUB_ENV
-          echo "${{ toJSON(inputs) }}"
 
       - name: Get version info from pom
-        if: ${{ contains(inputs.NPM_BUILD, 'false') && ( inputs.BUILD_ARTIFACT != 'false' )  && ( inputs.ONLY_DOCKER == false ) }}
+        if: ${{ contains(inputs.NPM_BUILD, 'false') && inputs.BUILD_ARTIFACT != 'false' && inputs.ONLY_DOCKER == false }}
         id: getPomVersion
         uses: mavrosxristoforos/get-xml-info@1.1.1
         with:
@@ -70,22 +119,19 @@ jobs:
           xpath: /*[local-name()="project"]/*[local-name()="version"]
 
       - name: Unzip and extract for docker build
-        if: ${{ contains(inputs.NPM_BUILD, 'false' ) && ( inputs.BUILD_ARTIFACT != 'false' )  && ( inputs.ONLY_DOCKER == true )}}
-        run: |
-          unzip "${{ inputs.BUILD_ARTIFACT }}.zip" -d "${{ inputs.SERVICE_LOCATION }}"
+        if: ${{ contains(inputs.NPM_BUILD, 'false') && inputs.BUILD_ARTIFACT != 'false' && inputs.ONLY_DOCKER == true }}
+        run: unzip "${{ inputs.BUILD_ARTIFACT }}.zip" -d "${{ inputs.SERVICE_LOCATION }}"
 
       - name: Unzip and extract for maven
-        if: ${{ contains(inputs.NPM_BUILD, 'false' ) && ( inputs.BUILD_ARTIFACT != 'false' ) && ( inputs.ONLY_DOCKER == false ) }}
-        run: |
-          unzip -uj "${{ inputs.BUILD_ARTIFACT }}.zip" "${{ inputs.SERVICE_LOCATION }}/target/*" -d "${{ env.SERVICE_LOCATION }}/target/"
+        if: ${{ contains(inputs.NPM_BUILD, 'false') && inputs.BUILD_ARTIFACT != 'false' && inputs.ONLY_DOCKER == false }}
+        run: unzip -uj "${{ inputs.BUILD_ARTIFACT }}.zip" "${{ inputs.SERVICE_LOCATION }}/target/*" -d "${{ env.SERVICE_LOCATION }}/target/"
 
       - name: Unzip and extract for npm
-        if: ${{ contains(inputs.NPM_BUILD, 'true' ) && ( inputs.BUILD_ARTIFACT != false )  && ( inputs.ONLY_DOCKER == false )}}
-        run: |
-          unzip "${{ inputs.BUILD_ARTIFACT }}.zip" "dist/*" -d "${{ inputs.SERVICE_LOCATION }}"
+        if: ${{ contains(inputs.NPM_BUILD, 'true') && inputs.BUILD_ARTIFACT != false && inputs.ONLY_DOCKER == false }}
+        run: unzip "${{ inputs.BUILD_ARTIFACT }}.zip" "dist/*" -d "${{ inputs.SERVICE_LOCATION }}"
 
       - name: Get current date
-        run: echo "BUILD_TIME=$(date +'%Y-%m-%d-%H-%M-%S')"  >> $GITHUB_ENV
+        run: echo "BUILD_TIME=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
 
       - name: Build check for Docker label
         run: |
@@ -99,11 +145,17 @@ jobs:
               exit 1;
             fi
           done
-
+          
       - name: Build image
         run: |
           cd ${{ inputs.SERVICE_LOCATION }}
-          docker build . --build-arg SOURCE=mosip --build-arg COMMIT_HASH=$(git rev-parse HEAD) --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --build-arg BUILD_TIME=$BUILD_TIME --file Dockerfile --tag ${{ env.SERVICE_NAME }}
+          docker build . \
+            --build-arg SOURCE=mosip \
+            --build-arg COMMIT_HASH=$(git rev-parse HEAD) \
+            --build-arg COMMIT_ID=$(git rev-parse --short HEAD) \
+            --build-arg BUILD_TIME=$BUILD_TIME \
+            --file $DOCKERFILE_NAME \
+            --tag ${{ env.SERVICE_NAME }}
 
       - name: Log into registry
         if: "${{ github.event_name != 'pull_request' }}"
@@ -113,67 +165,29 @@ jobs:
         if: "${{ github.event_name != 'pull_request' }}"
         run: |
           IMAGE_ID=$NAMESPACE/$SERVICE_NAME
-          
-          # Change all uppercase to lowercase
           IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
           echo "push version ${{steps.getPomVersion.outputs.info}}"
           if [[ $BRANCH_NAME == master ]]; then
-          VERSION=latest
+            VERSION=latest
           else
-          VERSION=$BRANCH_NAME
+            VERSION=$BRANCH_NAME
           fi
           echo IMAGE_ID=$IMAGE_ID
           echo VERSION=$VERSION
           if [[ -z "${{ inputs.SQUASH_LAYERS }}" ]]; then
             echo "No squash layer input provided, using standard tagging and push"
             docker tag $SERVICE_NAME $IMAGE_ID:$VERSION
+            docker push $IMAGE_ID:$VERSION
           else
             echo "Squashing image before push..."
             docker-squash -f ${{ inputs.SQUASH_LAYERS }} -t $IMAGE_ID:$VERSION $SERVICE_NAME
+            docker push $IMAGE_ID:$VERSION
           fi
-          docker push $IMAGE_ID:$VERSION
 
       - uses: 8398a7/action-slack@v3
         with:
           status: ${{ job.status }}
-          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
+          fields: repo,message,author,commit,workflow,job
         env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
-        if: "${{ github.event_name != 'pull_request' && failure() }}" # Pick up events even if the job fails or is canceled.
-
-  build-docker-warning:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Check Dockerfile for forbidden organizations and tags
-        if: |
-          (github.event_name == 'push' && startsWith(github.ref_name, 'release')) ||
-          (github.event_name == 'pull_request' && startsWith(github.base_ref, 'release')) ||
-          (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/release'))
-        run: |
-          cd ${{ inputs.SERVICE_LOCATION }}
-          
-          # Check if Dockerfile exists
-          if [ ! -f Dockerfile ]; then
-            echo "Error: Dockerfile not found."
-            exit 1
-          else
-            # Search for forbidden base images or tags
-            forbidden_found=false
-            if grep -E "FROM (mosipdev|mosipqa)/" Dockerfile; then
-              echo "Error: Dockerfile contains forbidden base image from 'mosipdev' or 'mosipqa' organization."
-              forbidden_found=true
-            fi
-            if grep -E "FROM .*:(latest|develop)" Dockerfile; then
-              echo "Error: Dockerfile contains forbidden base image tag 'latest' or 'develop'."
-              forbidden_found=true
-            fi
-            if [ "$forbidden_found" = true ]; then
-              echo "Error: Dockerfile contains forbidden base images or tags."
-              exit 1
-            else
-              echo "Dockerfile check passed: No forbidden organizations or tags found."
-            fi
-          fi
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        if: "${{ github.event_name != 'pull_request' && failure() }}"
